'use client';
import { useEffect,useState } from 'react';
import styles from './admin.module.css';

const columns=[['played','PJ'],['won','PG'],['drawn','PE'],['lost','PP'],['walkovers','WO'],['pointsFor','PF'],['pointsAgainst','PC'],['difference','DP'],['points','PTS']];
const headerMap={equipo:'name',team:'name',nombre:'name',pj:'played',pg:'won',pe:'drawn',pp:'lost',wo:'walkovers',pf:'pointsFor',pc:'pointsAgainst',dp:'difference',pts:'points'};
const template='equipo,pj,pg,pe,pp,wo,pf,pc,dp,pts\nLA CAPITANA A,11,8,1,2,0,141,93,48,25';

function parseLine(line,delimiter){const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){value+='"';i++}else if(char==='"'){quoted=!quoted}else if(char===delimiter&&!quoted){cells.push(value.trim());value=''}else value+=char}cells.push(value.trim());return cells}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delimiter=lines[0].includes(';')?';':',';const headers=parseLine(lines[0],delimiter).map(h=>headerMap[h.trim().toLowerCase()]);return lines.slice(1).map(line=>{const values=parseLine(line,delimiter);return Object.fromEntries(headers.map((header,index)=>[header,header==='name'?values[index]:Number(values[index]||0)]).filter(([key])=>key))}).filter(team=>team.name)}

export default function RankingManager(){const [teams,setTeams]=useState([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function load(){const response=await fetch('/api/admin/ranking');if(response.ok)setTeams(await response.json())}
  useEffect(()=>{load()},[]);
  function update(index,field,value){setTeams(current=>current.map((team,i)=>i===index?{...team,[field]:field==='name'?value:Number(value)}:team))}
  async function save(team){setBusy(true);setMessage('');const response=await fetch('/api/admin/ranking',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(team)});setBusy(false);setMessage(response.ok?`${team.name} actualizado.`:(await response.json()).error||'No se pudo guardar.');if(response.ok)load()}
  async function upload(event){const file=event.target.files?.[0];if(!file)return;const imported=parseCsv(await file.text());if(!imported.length){setMessage('El CSV no tiene filas válidas.');return}setBusy(true);const response=await fetch('/api/admin/ranking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({teams:imported})});setBusy(false);setMessage(response.ok?`${imported.length} equipos importados.`:(await response.json()).error||'No se pudo importar.');if(response.ok)load();event.target.value=''}
  return <section className={`${styles.panel} ${styles.rankingPanel}`} id="ranking"><div className={styles.panelHeader}><div><p>CONTENIDO PRINCIPAL</p><h2>Ranking oficial</h2><span>Edita una fila o reemplaza la tabla completa desde CSV.</span></div><div className={styles.rankingActions}><a href={`data:text/csv;charset=utf-8,${encodeURIComponent(template)}`} download="ranking-apg.csv">Descargar plantilla</a><label>Importar CSV<input type="file" accept=".csv,text/csv" onChange={upload} disabled={busy}/></label></div></div>{message&&<p className={styles.notice}>{message}</p>}<div className={styles.adminTableWrap}><table className={styles.adminRanking}><thead><tr><th>#</th><th>Equipo</th>{columns.map(([,label])=><th key={label}>{label}</th>)}<th/></tr></thead><tbody>{teams.map((team,index)=><tr key={team.id}><td>{index+1}</td><td><input className={styles.teamInput} value={team.name} onChange={e=>update(index,'name',e.target.value)}/></td>{columns.map(([field])=><td key={field}><input type="number" value={team[field]} onChange={e=>update(index,field,e.target.value)}/></td>)}<td><button onClick={()=>save(team)} disabled={busy}>Guardar</button></td></tr>)}</tbody></table></div>{!teams.length&&<p className={styles.empty}>Aplica la migración de ranking o importa un CSV para comenzar.</p>}</section>}
