import styles from '../public.module.css';

export const metadata = { title: 'Nuestra historia | APG' };

export default function About() {
  return <main className={styles.page}>
    <header className={`${styles.container} ${styles.hero}`}><div><p className={styles.eyebrow}>Asociación Perú Gateball</p><h1>Nuestra historia.</h1></div><p className={styles.heroText}>Una institución nacida para promover el gateball en el Perú y cultivar unión, amistad y respeto a través del deporte.</p></header>
    <section className={`${styles.container} ${styles.section}`}><div className={`${styles.storyLead} ${styles.reveal}`}><div className={styles.storyCopy}><p>La Asociación Perú Gateball es una organización estable de personas naturales que, a través de una actividad común pero en un fin no lucrativo, promueve en el Perú el deporte del gateball y las competencias que contribuyen al sano desarrollo físico y mental de sus cultores.</p><p>La institución se constituyó inicialmente como Comisión Peruana de Gateball en 1987 y fue reconocida como deporte ante el Instituto Peruano del Deporte el 8 de diciembre de ese año. Su primer presidente fue el Sr. Mario Akamine Oshiro.</p></div><div className={styles.storyFacts}><span>Desde</span><strong>1987</strong><p>Promoviendo el gateball y fortaleciendo la comunidad.</p></div></div></section>
    <section className={`${styles.container} ${styles.section}`}><div className={styles.timeline}><div className={styles.timelineMark}><span>1983</span><i>—</i><span>Actualidad</span></div><div className={styles.timelineCopy}><p className={styles.eyebrow}>Historia y organización</p><h2>Los primeros pasos del gateball en el Perú.</h2><p>Los primeros esfuerzos fueron realizados por Don Luis Masahiro Nakada, quien a su retorno de São Paulo, Brasil, trajo los implementos necesarios para el juego. Junto a Don Manuel Matsuda inició el proceso de introducción y desarrollo del gateball durante 1983 y 1984 en el campo de la actual AOP.</p><p>Seiju Namisato, Minoru Nakasato, Yoshio Miyagawa, Yoshitaka Higa y Katsuno Oshiro continuaron su difusión en el Centro Cultural Peruano Japonés. Posteriormente, la Asociación Perú Gateball comenzó sus actividades en la Asociación Estadio La Unión (AELU).</p><div className={styles.stats}><div className={styles.stat}><strong>1987</strong><span>Año de constitución</span></div><div className={styles.stat}><strong>250+</strong><span>Jugadores asociados activos</span></div><div className={styles.stat}><strong>38</strong><span>Equipos participantes</span></div></div></div></div></section>
    <section className={`${styles.container} ${styles.section}`}><div className={styles.legacy}><h2>Una comunidad conectada con el mundo.</h2><div><p>En 1986 se formalizó la Federación Sudamericana de Gateball, con sede en Brasil. La APG se encuentra afiliada a la Unión Mundial de Gateball, con sede en Japón, institución que establece las reglas y organiza los campeonatos mundiales.</p><p>Los torneos mundiales se realizaron anualmente entre 1986 y 1990; desde 1994 se celebran cada cuatro años. Actualmente, el presidente de la Asociación Perú Gateball es el Sr. José Watanabe Kaway.</p></div></div></section>
  </main>;
}
