-- APG core schema. Apply with `npx supabase db push` after `supabase link`.
create table public.admins (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null default 'Administrador APG',
  created_at timestamptz not null default now()
);

create table public.players (
  id bigint generated by default as identity primary key,
  full_name text not null,
  club text,
  points integer not null default 0 check (points >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  city text,
  points integer not null default 0 check (points >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date not null,
  location text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'cancelled')),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index events_date_idx on public.events (event_date);
create index players_points_idx on public.players (points desc);
create index teams_points_idx on public.teams (points desc);

-- The application reaches the database through server-only PostgreSQL routes.
-- RLS prevents accidental exposure through Supabase's generated Data API.
alter table public.admins enable row level security;
alter table public.players enable row level security;
alter table public.teams enable row level security;
alter table public.events enable row level security;

-- The public site may read published events and the active team ranking only.
create policy "public reads published events" on public.events for select to anon, authenticated using (status = 'published');
create policy "public reads active teams" on public.teams for select to anon, authenticated using (active = true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('apg-assets', 'apg-assets', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'application/pdf'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "public reads APG assets" on storage.objects for select to public using (bucket_id = 'apg-assets');
